// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN3IOzd_c9_PHbuzjimZ3rs1DlFLXyoNI',
    appId: '1:944599826410:web:b6df84a506a6784d2d7c93',
    messagingSenderId: '944599826410',
    projectId: 'news-app-76f0d',
    authDomain: 'news-app-76f0d.firebaseapp.com',
    storageBucket: 'news-app-76f0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKPsOZFGsiVY7j9DQJOzs_5sDvW3w-AeE',
    appId: '1:944599826410:android:088726b3989247ee2d7c93',
    messagingSenderId: '944599826410',
    projectId: 'news-app-76f0d',
    storageBucket: 'news-app-76f0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZxcn4YCGlyYwGBms4mK4ayNq5CKOCeWA',
    appId: '1:944599826410:ios:7d035192ee2edbaf2d7c93',
    messagingSenderId: '944599826410',
    projectId: 'news-app-76f0d',
    storageBucket: 'news-app-76f0d.firebasestorage.app',
    iosClientId: '944599826410-4qkfjttpqm3otovnbaiqkmqkngts5p3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZxcn4YCGlyYwGBms4mK4ayNq5CKOCeWA',
    appId: '1:944599826410:ios:7d035192ee2edbaf2d7c93',
    messagingSenderId: '944599826410',
    projectId: 'news-app-76f0d',
    storageBucket: 'news-app-76f0d.firebasestorage.app',
    iosClientId: '944599826410-4qkfjttpqm3otovnbaiqkmqkngts5p3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN3IOzd_c9_PHbuzjimZ3rs1DlFLXyoNI',
    appId: '1:944599826410:web:4f8e1c1ed08b34c42d7c93',
    messagingSenderId: '944599826410',
    projectId: 'news-app-76f0d',
    authDomain: 'news-app-76f0d.firebaseapp.com',
    storageBucket: 'news-app-76f0d.firebasestorage.app',
  );
}
